version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d              # Custom Nginx configuration
      - ./certbot/conf:/etc/letsencrypt               # SSL certificates
      - ./certbot/www:/var/www/certbot                # Webroot for Certbot
    restart: unless-stopped
    network_mode: host

  # launch only once to issue certificate
  certbot-issue:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt               # SSL certificates
      - ./certbot/www:/var/www/certbot                # Webroot for Certbot
    profiles: [ init ]
    entrypoint: "certbot certonly --standalone -d your-domain.com"

  certbot-renew:
    image: certbot/certbot:latest
    container_name: certbot-renew
    volumes:
      - ./certbot/conf:/etc/letsencrypt               # SSL certificates
      - ./certbot/www:/var/www/certbot                # Webroot for Certbot
    network_mode: host
    profiles: [ renew ]
    entrypoint: "certbot renew --standalone"